'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const jsonPath = path.join(root, 'assets', 'iso3166_countries.json');
const outPath = path.join(root, 'lib', 'data', 'iso3166_country_choices.dart');

const raw = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
const rows = raw
  .map((r) => ({ code: r['alpha-2'], name: r.name }))
  .filter((r) => r.code && r.name)
  .sort((a, b) => a.name.localeCompare(b.name, 'en'));

function dartStringForDoubleQuotes(s) {
  return s
    .replace(/\\/g, '\\\\')
    .replace(/\$/g, '\\$')
    .replace(/"/g, '\\"');
}

const body = rows
  .map((r) => `  {'code': '${r.code}', 'name': "${dartStringForDoubleQuotes(r.name)}"},`)
  .join('\n');

const header = `// GENERATED by tool/generate_iso_countries_dart.cjs from assets/iso3166_countries.json
// Do not edit by hand — re-run: node tool/generate_iso_countries_dart.cjs
`;

const file = `${header}
const List<Map<String, String>> kIso3166CountryChoices = [
${body}
];
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, file, 'utf8');
console.log('Wrote', outPath, 'rows', rows.length);
